source 'https://rubygems.org'
gem 'sfn'
gem 'sparkle-pack-aws-my-rds',             :git => 'https://github.com/gswallow/sparkle-pack-aws-my-rds.git'
gem 'sparkle-pack-aws-my-security-groups', :git => 'https://github.com/gswallow/sparkle-pack-aws-my-security-groups.git'
gem 'sparkle-pack-aws-my-subnets',         :git => 'https://github.com/gswallow/sparkle-pack-aws-my-subnets.git'
gem 'sparkle-pack-aws-my-route53-zones',   :git => 'https://github.com/gswallow/sparkle-pack-aws-my-route53-zones.git'
gem 'sparkle-pack-aws-availability-zones'
